export interface testData{
    name: string;
    email: string;
    body: string;
}

// Generated by https://quicktype.io

export interface Users {
    users: User[];
}

export interface User {
    id:       number;
    name:     string;
    email:    string;
    password: string;
    valid:    boolean;
}
